import os
import re
import sys
import clang.cindex

LLVM_PATH = "C:/Program Files/LLVM/bin"

if os.path.exists(os.path.join(LLVM_PATH, "libclang.dll")):
    clang.cindex.Config.set_library_path(LLVM_PATH)
else:
    print(f"BŁĄD: Nie znaleziono libclang.dll w katalogu: {LLVM_PATH}")
    sys.exit(1)


def to_screaming_snake(name):
    name = re.sub(r'(Component|Tag)$', '', name)
    s1 = re.sub('(.)([A-Z][a-z]+)', r'\1_\2', name)
    return re.sub('([a-z0-9])([A-Z])', r'\1_\2', s1).upper()


def get_component_group(node, file_content):
    """
    Sprawdza, czy nad strukturą znajduje się komentarz @Component(GRUPA).
    Bezpiecznie sprawdza zakres linii pliku.
    """
    if node.extent.start.file is None:
        return None

    start_line = node.extent.start.line
    lines = file_content.split('\n')
    num_lines = len(lines)

    # Zabezpieczamy zakres przed wyjściem poniżej 0 i powyżej rzeczywistej liczby linii
    low_bound = max(0, start_line - 4)
    high_bound = min(num_lines, start_line - 1)

    for i in range(low_bound, high_bound):
        if i < num_lines:
            match = re.search(r'@Component\((\w+)\)', lines[i])
            if match:
                return match.group(1)
    return None


def should_ignore_field(node, file_content):
    """
    Sprawdza, czy bezpośrednio nad zmienną znajduje się komentarz //@Ignore
    Bezpiecznie sprawdza zakres linii pliku.
    """
    start_line = node.extent.start.line
    lines = file_content.split('\n')
    num_lines = len(lines)

    # Sprawdzamy linijkę tuż nad zmienną (indeks start_line - 2), upewniając się, że istnieje
    target_idx = start_line - 2
    if 0 <= target_idx < num_lines:
        prev_line = lines[target_idx].strip().replace(" ", "")
        if "//@Ignore" in prev_line:
            return True
    return False


def to_snake_case(name):
    s1 = re.sub('(.)([A-Z][a-z]+)', r'\1_\2', name)
    return re.sub('([a-z0-9])([A-Z])', r'\1_\2', s1).lower()

def run_codegen():
    groups = {"REQUIRED": [], "ADDITIONAL": [], "UTILITY": [], "TAG": []}
    struct_fields = []

    index = clang.cindex.Index.create()

    components_dir = "Src/Components.h"

    with open(components_dir, "r", encoding="utf-8") as f:
        file_content = f.read()
        tu = index.parse(components_dir, args=['-std=c++17',
                                               '-x', 'c++-header',
                                               '-fparse-all-comments',
                                               '-ferror-limit=0',
                                               '-fms-compatibility',
                                               '-Wno-invalid-token-paste'
                                               ], options=(
                clang.cindex.TranslationUnit.PARSE_INCOMPLETE |
                clang.cindex.TranslationUnit.PARSE_SKIP_FUNCTION_BODIES |
                clang.cindex.TranslationUnit.PARSE_DETAILED_PROCESSING_RECORD
        ))

        # Przeszukujemy drzewo AST wygenerowane przez Clang
        for node in tu.cursor.walk_preorder():
            # Interesują nas tylko deklaracje struktur/klas z pliku źródłowego
            if node.kind in (clang.cindex.CursorKind.STRUCT_DECL, clang.cindex.CursorKind.CLASS_DECL):
                if node.location.file and node.location.file.name == components_dir:
                    group = get_component_group(node, file_content)
                    if group in groups:
                        struct_name = node.spelling
                        tag = to_screaming_snake(struct_name)
                        groups[group].append((tag, struct_name))
                        # Szukamy zmiennych należących do tej struktury
                        fields = []
                        for child in node.get_children():
                            if child.kind == clang.cindex.CursorKind.FIELD_DECL:
                                if not should_ignore_field(child, file_content):
                                    fields.append(child.spelling)

                        if fields:
                            struct_fields.append((struct_name, fields))

    # Generowanie pliku nagłówkowego
    output_path_h = "Src/GeneratedComponents.h"
    with open(output_path_h, "w", encoding="utf-8") as f:
        f.write("// ==========================================================\n")
        f.write("// AUTOMATICALLY GENERATED BY CODEGEN.PY (LIBCLANG PARSER). DO NOT EDIT.\n")
        f.write("// ==========================================================\n\n")
        f.write("#pragma once\n\n")

        f.write("#include \"Components.h\"\n")
        f.write("#include \"include/visit_struct/visit_struct.hpp\"\n\n")

        for group, items in groups.items():
            macro_name = f"{group.capitalize()}ComponentNamesMacro"
            if not items:
                f.write(f"#define {macro_name}(X)\n\n")
                continue
            macro_lines = " \\\n    ".join([f"X({tag}, {name})" for tag, name in items])
            f.write(f"#define {macro_name}(X) \\\n    {macro_lines}\n\n")

        f.write("#define AllComponentNamesMacro(X) \\\n"
                "    RequiredComponentNamesMacro(X) \\\n"
                "    UtilityComponentNamesMacro(X) \\\n"
                "    AdditionalComponentNamesMacro(X)\n\n")

        f.write("// ==========================================================\n")
        f.write("// ENUM GENERATION\n")
        f.write("// ==========================================================\n")
        f.write("enum class RequiredComponentType\n")
        f.write("{\n")
        f.write("\t#define X(e, t) e,\n")
        f.write("\t\tRequiredComponentNamesMacro(X)\n")
        f.write("\t#undef X\n")
        f.write("\tCOUNT\n")
        f.write("};\n\n")
        f.write("enum class AdditionalComponentType\n")
        f.write("{\n")
        f.write("\t#define X(e, t) e,\n")
        f.write("\t\tAdditionalComponentNamesMacro(X)\n")
        f.write("\t#undef X\n")
        f.write("\tCOUNT\n")
        f.write("};\n\n")
        f.write("enum class UtilityComponentType\n")
        f.write("{\n")
        f.write("\t#define X(e, t) e,\n")
        f.write("\t\tUtilityComponentNamesMacro(X)\n")
        f.write("\t#undef X\n")
        f.write("\tCOUNT\n")
        f.write("};\n\n")
        f.write("enum class TagComponentType\n")
        f.write("{\n")
        f.write("\t#define X(e, t) e,\n")
        f.write("\t\tTagComponentNamesMacro(X)\n")
        f.write("\t#undef X\n")
        f.write("\tCOUNT\n")
        f.write("};\n\n")
        f.write("enum class ComponentType\n")
        f.write("{\n")
        f.write("\t#define X(e, t) e,\n")
        f.write("\t\tAllComponentNamesMacro(X)\n")
        f.write("\t\tTagComponentNamesMacro(X)\n")
        f.write("\t#undef X\n")
        f.write("\tCOUNT\n")
        f.write("};\n\n")

        f.write("// ==========================================================\n")
        f.write("// AUTOMATIC REFLECTION REGISTRATION\n")
        f.write("// ==========================================================\n")
        for struct in struct_fields:
            struct_name, fields = struct

            f.write(f"void to_json(JSON& j, const {struct_name}& component);\n")
            f.write(f"void from_json(const JSON& j, {struct_name}& component);\n")
            fields = ", ".join(fields)
            f.write(f"VISITABLE_STRUCT({struct_name}, {fields});\n\n")

    output_path_cpp = "Src/GeneratedComponents.cpp"
    with open(output_path_cpp, "w", encoding="utf-8") as f:
        f.write("// ==========================================================\n")
        f.write("// AUTOMATICALLY GENERATED BY CODEGEN.PY (LIBCLANG PARSER). DO NOT EDIT.\n")
        f.write("// ==========================================================\n")
        f.write("#include \"GeneratedComponents.h\"\n\n")

        for struct in struct_fields:
            struct_name, fields = struct

            f.write(f"void to_json(JSON& j, const {struct_name}& component)\n")
            f.write("{\n")
            for field in fields:
                f.write(f"\tj[\"{to_snake_case(field)}\"] = component.{field};\n")
            f.write("}\n\n")

            f.write(f"void from_json(const JSON& j, {struct_name}& component)\n")
            f.write("{\n")
            for field in fields:
                f.write(f"\tReadJsonValue(component.{field}, j, \"{to_snake_case(field)}\", component.{field});\n")
            f.write("}\n\n\n")


if __name__ == "__main__":
    run_codegen()
