import re
import clang.cindex

from Python.config import init_libclang
from Python.utils import to_screaming_snake, to_snake_case, to_screaming_space, save_if_changed

def get_component_group(node, file_content):
    """
    Sprawdza, czy nad strukturą znajduje się komentarz @Component(GRUPA).
    Bezpiecznie sprawdza zakres linii pliku.
    """
    if node.extent.start.file is None:
        return None

    start_line = node.extent.start.line
    lines = file_content.split('\n')
    num_lines = len(lines)

    # Zabezpieczamy zakres przed wyjściem poniżej 0 i powyżej rzeczywistej liczby linii
    low_bound = max(0, start_line - 2)
    high_bound = min(num_lines, start_line - 1)

    for i in range(low_bound, high_bound):
        if i < num_lines:
            match = re.search(r'@Component\((\w+)\)', lines[i])
            if match:
                return match.group(1)
    return None


def should_ignore_field(node, file_content):
    """
    Sprawdza, czy bezpośrednio nad zmienną znajduje się komentarz //@Ignore
    Bezpiecznie sprawdza zakres linii pliku.
    """
    start_line = node.extent.start.line
    lines = file_content.split('\n')
    num_lines = len(lines)

    # Sprawdzamy linijkę tuż nad zmienną (indeks start_line - 2), upewniając się, że istnieje
    target_idx = start_line - 2
    if 0 <= target_idx < num_lines:
        prev_line = lines[target_idx].strip().replace(" ", "")
        if "//@Ignore" in prev_line:
            return True
    return False



def run_codegen():
    groups = {"REQUIRED": [], "ADDITIONAL": [], "UTILITY": [], "TAG": []}
    struct_fields = []

    index = clang.cindex.Index.create()

    components_dir = "Components.h"

    with open(components_dir, "r", encoding="utf-8") as f:
        file_content = f.read()
        tu = index.parse(components_dir, args=['-std=c++17',
                                               '-x', 'c++-header',
                                               '-fparse-all-comments',
                                               '-ferror-limit=0',
                                               '-fms-compatibility',
                                               '-Wno-invalid-token-paste'
                                               ], options=(
                clang.cindex.TranslationUnit.PARSE_INCOMPLETE |
                clang.cindex.TranslationUnit.PARSE_SKIP_FUNCTION_BODIES |
                clang.cindex.TranslationUnit.PARSE_DETAILED_PROCESSING_RECORD
        ))

        # Przeszukujemy drzewo AST wygenerowane przez Clang
        for node in tu.cursor.walk_preorder():
            # Interesują nas tylko deklaracje struktur/klas z pliku źródłowego
            if node.kind in (clang.cindex.CursorKind.STRUCT_DECL, clang.cindex.CursorKind.CLASS_DECL):
                if node.location.file and node.location.file.name == components_dir:
                    group = get_component_group(node, file_content)
                    if group in groups:
                        struct_name = node.spelling
                        tag = to_screaming_snake(struct_name)
                        groups[group].append((tag, struct_name))
                        # Szukamy zmiennych należących do tej struktury
                        fields = []
                        for child in node.get_children():
                            if child.kind == clang.cindex.CursorKind.FIELD_DECL:
                                if not should_ignore_field(child, file_content):
                                    fields.append(child.spelling)

                        if fields:
                            struct_fields.append((struct_name, fields))

    # Generowanie pliku nagłówkowego
    content = ["// ==========================================================\n",
               "// AUTOMATICALLY GENERATED BY componentgen.py (LIBCLANG PARSER). DO NOT EDIT.\n",
               "// ==========================================================\n\n", "#pragma once\n\n",
               "#include \"Components.h\"\n", "#include \"include/visit_struct/visit_struct.hpp\"\n\n"]

    for group, items in groups.items():
        macro_name = f"{group.capitalize()}ComponentNamesMacro"
        if not items:
            content.append(f"#define {macro_name}(X)\n\n")
            continue
        macro_lines = " \\\n    ".join([f"X({tag}, {name})" for tag, name in items])
        content.append(f"#define {macro_name}(X) \\\n    {macro_lines}\n\n")

    content.append("#define AllComponentNamesMacro(X) \\\n"
            "    RequiredComponentNamesMacro(X) \\\n"
            "    UtilityComponentNamesMacro(X) \\\n"
            "    AdditionalComponentNamesMacro(X)\n\n")

    content.append("// ==========================================================\n")
    content.append("// ENUM GENERATION\n")
    content.append("// ==========================================================\n")
    content.append("enum class RequiredComponentType\n")
    content.append("{\n")
    content.append("\t#define X(e, t) e,\n")
    content.append("\t\tRequiredComponentNamesMacro(X)\n")
    content.append("\t#undef X\n")
    content.append("\tCOUNT\n")
    content.append("};\n\n")
    content.append("enum class AdditionalComponentType\n")
    content.append("{\n")
    content.append("\t#define X(e, t) e,\n")
    content.append("\t\tAdditionalComponentNamesMacro(X)\n")
    content.append("\t#undef X\n")
    content.append("\tCOUNT\n")
    content.append("};\n\n")
    content.append("enum class UtilityComponentType\n")
    content.append("{\n")
    content.append("\t#define X(e, t) e,\n")
    content.append("\t\tUtilityComponentNamesMacro(X)\n")
    content.append("\t#undef X\n")
    content.append("\tCOUNT\n")
    content.append("};\n\n")
    content.append("enum class TagComponentType\n")
    content.append("{\n")
    content.append("\t#define X(e, t) e,\n")
    content.append("\t\tTagComponentNamesMacro(X)\n")
    content.append("\t#undef X\n")
    content.append("\tCOUNT\n")
    content.append("};\n\n")
    content.append("enum class ComponentType\n")
    content.append("{\n")
    content.append("\t#define X(e, t) e,\n")
    content.append("\t\tAllComponentNamesMacro(X)\n")
    content.append("\t\tTagComponentNamesMacro(X)\n")
    content.append("\t#undef X\n")
    content.append("\tCOUNT\n")
    content.append("};\n\n")

    content.append("// ==========================================================\n")
    content.append("// AUTOMATIC REFLECTION REGISTRATION\n")
    content.append("// ==========================================================\n")
    for struct in struct_fields:
        struct_name, fields = struct

        content.append(f"void to_json(JSON& j, const {struct_name}& component);\n")
        content.append(f"void from_json(const JSON& j, {struct_name}& component);\n")
        fields = ", ".join(fields)
        content.append(f"VISITABLE_STRUCT({struct_name}, {fields});\n\n")

    output_path = "GeneratedComponents.h"
    save_if_changed(output_path, "".join(content))

    content = ["// ==========================================================\n",
               "// AUTOMATICALLY GENERATED BY CODEGEN.PY (LIBCLANG PARSER). DO NOT EDIT.\n",
               "// ==========================================================\n",
               "#include \"GeneratedComponents.h\"\n\n"]

    for struct in struct_fields:
        struct_name, fields = struct

        content.append("// ==========================================================\n")
        content.append(f"// {to_screaming_space(struct_name)}\n")
        content.append("// ==========================================================\n")
        content.append(f"void to_json(JSON& j, const {struct_name}& component)\n")
        content.append("{\n")
        for field in fields:
            content.append(f"\tj[\"{to_snake_case(field)}\"] = component.{field};\n")
        content.append("}\n\n")

        content.append(f"void from_json(const JSON& j, {struct_name}& component)\n")
        content.append("{\n")
        for field in fields:
            content.append(f"\tReadJsonValue(component.{field}, j, \"{to_snake_case(field)}\", component.{field});\n")
        content.append("}\n\n")

    output_path = "GeneratedComponents.cpp"
    save_if_changed(output_path, "".join(content))


if __name__ == "__main__":
    init_libclang()
    run_codegen()
