// ==========================================================
// AUTOMATICALLY GENERATED BY CODEGEN.PY (LIBCLANG PARSER). DO NOT EDIT.
// ==========================================================

#pragma once

#include "Components.h"
#include "include/visit_struct/visit_struct.hpp"

#define RequiredComponentNamesMacro(X) \
    X(TAG, TagComponent)

#define AdditionalComponentNamesMacro(X) \
    X(PARALLAX, ParallaxComponent) \
    X(RENDERER, RendererComponent) \
    X(MOVE_SPEED, MoveSpeedComponent) \
    X(PATROL, PatrolComponent) \
    X(ROUND, RoundComponent) \
    X(ANIMATOR, AnimatorComponent) \
    X(MAIN_MENU_TEXT, MainMenuText) \
    X(MAIN_MENU, MainMenuComponent) \
    X(TEXT, TextComponent)

#define UtilityComponentNamesMacro(X) \
    X(ORDER, OrderComponent) \
    X(ENTITY_GROUP, EntityGroupComponent) \
    X(ENTITY_GROUP_CHILD, EntityGroupChildComponent)

#define TagComponentNamesMacro(X) \
    X(SCALE_TO_SCREEN, ScaleToScreenTag)

#define AllComponentNamesMacro(X) \
    RequiredComponentNamesMacro(X) \
    UtilityComponentNamesMacro(X) \
    AdditionalComponentNamesMacro(X)

// ==========================================================
// ENUM GENERATION
// ==========================================================
enum class RequiredComponentType
{
	#define X(e, t) e,
		RequiredComponentNamesMacro(X)
	#undef X
	COUNT
};

enum class AdditionalComponentType
{
	#define X(e, t) e,
		AdditionalComponentNamesMacro(X)
	#undef X
	COUNT
};

enum class UtilityComponentType
{
	#define X(e, t) e,
		UtilityComponentNamesMacro(X)
	#undef X
	COUNT
};

enum class TagComponentType
{
	#define X(e, t) e,
		TagComponentNamesMacro(X)
	#undef X
	COUNT
};

enum class ComponentType
{
	#define X(e, t) e,
		AllComponentNamesMacro(X)
		TagComponentNamesMacro(X)
	#undef X
	COUNT
};

// ==========================================================
// AUTOMATIC REFLECTION REGISTRATION
// ==========================================================
void to_json(JSON& j, const TagComponent& component);
void from_json(const JSON& j, TagComponent& component);
VISITABLE_STRUCT(TagComponent, Value);

void to_json(JSON& j, const OrderComponent& component);
void from_json(const JSON& j, OrderComponent& component);
VISITABLE_STRUCT(OrderComponent, Value);

void to_json(JSON& j, const ParallaxComponent& component);
void from_json(const JSON& j, ParallaxComponent& component);
VISITABLE_STRUCT(ParallaxComponent, Strength);

void to_json(JSON& j, const RendererComponent& component);
void from_json(const JSON& j, RendererComponent& component);
VISITABLE_STRUCT(RendererComponent, LayerOrder, Data);

void to_json(JSON& j, const EntityGroupComponent& component);
void from_json(const JSON& j, EntityGroupComponent& component);
VISITABLE_STRUCT(EntityGroupComponent, Entities);

void to_json(JSON& j, const EntityGroupChildComponent& component);
void from_json(const JSON& j, EntityGroupChildComponent& component);
VISITABLE_STRUCT(EntityGroupChildComponent, Value);

void to_json(JSON& j, const MoveSpeedComponent& component);
void from_json(const JSON& j, MoveSpeedComponent& component);
VISITABLE_STRUCT(MoveSpeedComponent, Value);

void to_json(JSON& j, const PatrolComponent& component);
void from_json(const JSON& j, PatrolComponent& component);
VISITABLE_STRUCT(PatrolComponent, From, To, Reversed);

void to_json(JSON& j, const RoundComponent& component);
void from_json(const JSON& j, RoundComponent& component);
VISITABLE_STRUCT(RoundComponent, Center, Radius, T);

void to_json(JSON& j, const AnimatorComponent& component);
void from_json(const JSON& j, AnimatorComponent& component);
VISITABLE_STRUCT(AnimatorComponent, Animation, FrameTime);

void to_json(JSON& j, const MainMenuText& component);
void from_json(const JSON& j, MainMenuText& component);
VISITABLE_STRUCT(MainMenuText, Position, Scale, Color);

void to_json(JSON& j, const MainMenuComponent& component);
void from_json(const JSON& j, MainMenuComponent& component);
VISITABLE_STRUCT(MainMenuComponent, TitleScale, CurrentPanel, SheepText, GoesText, DevileText);

void to_json(JSON& j, const TextComponent& component);
void from_json(const JSON& j, TextComponent& component);
VISITABLE_STRUCT(TextComponent, Position, FontSize, Value);

