import os
import json
from Python.utils import save_if_changed, to_screaming_snake

def run_codegen():
    resources_path = "..\\Resources\\Sprites"
    enums = []

    for root, dirs, _ in os.walk(resources_path):
        for d in dirs:
            enums.append((d, []))
            for _1, _2, files in os.walk(os.path.join(root, d)):
                for f in files:
                    if f.endswith(".json"):
                        path = os.path.join(root, d, str(f))
                        with open(path, "r") as file:
                            data = json.load(file)
                            file_name_full = os.path.basename(str(f))
                            file_name_without_json = os.path.splitext(file_name_full)[0]
                            file_name_without_config = os.path.splitext(file_name_without_json)[0]
                            file_name_without_extension = os.path.splitext(file_name_without_config)[0]
                            enums[len(enums) - 1][1].append((file_name_without_extension.replace(" ", "_"), data["id"]))

    """
    #pragma once
    #include <cstdint>
    
    enum class Characters : std::uint64_t
    {
        BISCUP_MAGIC = 15898488116535732747u,
        boss = 11610819148870425494u,
        demon1 = 13929246925859671961u,
        demon2 = 6627821916887444946,
        GoHero = 1823744527168627006,
        NUN_WALK = 451370562053028975,
        Pani = 7389731335850396888,
        Warrior = 5996614717713736678,
    };
    """

    content = ["// ==========================================================\n",
               "// AUTOMATICALLY GENERATED BY spriteenumgen.py. DO NOT EDIT.\n",
               "// ==========================================================\n", "#pragma once\n\n",
               "#include <cstdint>\n\n"]

    for enum in enums:
        content.append(f"enum {to_screaming_snake(enum[0])}\n")
        content.append("{\n")
        i = 0
        for sprite in enum[1]:
            content.append(f"\t{sprite[0]} = {i},\n")
            i += 1
        content.append(f"\t{enum[0]}_Count = {len(enum[1])},\n")
        content.append("};\n\n")

    for enum in enums:
        content.append(f"constexpr std::uint64_t {enum[0]}[{enum[0]}_Count]\n")
        content.append("{\n")
        for sprite in enum[1]:
            content.append(f"\t{sprite[1]}u,\n")
        content.append("};\n\n")

    output_path = "SpriteEnums.h"
    save_if_changed(output_path, "".join(content))

if __name__ == "__main__":
    run_codegen()