// ==========================================================
// AUTOMATICALLY GENERATED BY spriteenumgen.py. DO NOT EDIT.
// ==========================================================
#pragma once

#include <cstdint>

enum CHARACTERS
{
	BISCUP_MAGIC = 0,
	boss = 1,
	demon1 = 2,
	demon2 = 3,
	GoHero = 4,
	NUN_WALK = 5,
	Pani = 6,
	Warrior = 7,
	Characters_Count = 8,
};

enum ENVIRONMENT
{
	drzewo_1 = 0,
	drzewo_2 = 1,
	kwiatki = 2,
	scena_1 = 3,
	scena_2 = 4,
	scena_3 = 5,
	tlo = 6,
	trawa = 7,
	tło_2 = 8,
	Environment_Count = 9,
};

constexpr std::uint64_t Characters[Characters_Count]
{
	15898488116535732747u,
	11610819148870425494u,
	13929246925859671961u,
	6627821916887444946u,
	1823744527168627006u,
	451370562053028975u,
	7389731335850396888u,
	5996614717713736678u,
};

constexpr std::uint64_t Environment[Environment_Count]
{
	16458946972688209028u,
	17930921003739762144u,
	7613845110139607196u,
	12158023348458245399u,
	9307515472869628893u,
	9754995296934205449u,
	7072379239301553486u,
	2333685563216771788u,
	16239456127028044638u,
};

